#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

$birthDate = '1982-11-16';
$birthDays = new \Andrey9x\Dates\BirthDays($birthDate);
$totalDays = $birthDays->findTotalDays();

echo "$birthDate : $totalDays\n";



