#!/usr/bin/env php
<?php

include 'src/Dates/BirthDays.php';

$birthDate = "1982-11-16";
$birthDays = new \Andreyru\Dates\BirthDays($birthDate);
$totalDays = $birthDays->findTotalDays();

echo "$birthDate : $totalDays\n";



