#!/usr/bin/env php
<?php

$opts = getopt("b:");

$birthDate = $opts["b"] ?? "1982-11-16";
$todayDate = date("Y-m-d");

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs / 3600 / 24);

echo "$birthDate : $totalDays\n";



